#!/bin/bash
#  
#  See README file for Installation Guide. 
#
#  Interactive tool that helps you create a mount point directory (MPD)
#  for external mass storage devices (USB, SSD, etc..). Once the MPD
#  is created, mount your device to it and it will appear in your file
#  manager for easy accesibility.
#
#  -- Made this tool for learning purposes and to automate the task of
#     making a MPD for mass storage devices.
#  -- Variations of this script are under development to allow use of
#     the sub tools within.
#  -- REPO: https://github.com/Dynecs/SimpleInteractiveScripts.git
#
#
#  Copyright (C) 2022 Dynecs
#  dynecs_@outlook.com
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#           
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, see <https://www.gnu.org/licenses/>
#

echo ""
echo "Starting tool." | pv -qL 21
sleep .5
echo "Creating session directory '$USER' inside /run/media/ " | pv -qL 21
sleep 1
echo "One moment..." | pv -qL 21
	if 
		[ -d "/run/media/$USER" ]
	then
		echo ""
		sleep 2
     	        echo "Hmm... Session directory already exists." | pv -qL 21
		sleep .5	
		echo "- Skipping to subdirectory creation." | pv -qL 21
	else
		echo ""
		sleep .5
		echo "Calling on 'mkdir' command." | pv -qL 21
		sleep .5
		sudo mkdir -v /run/media/$USER | pv -qL 21
		echo ""
		sleep .5
		echo "- Moving to subdirectory creation." | pv -qL 21
	fi
echo ""
sleep .5
echo "What would you like to name this subdirectory?" | pv -qL 21
read REPLY
sleep .5
	if
		[ -d "/run/media/$USER/$REPLY" ]
	then
		echo ""
		sleep .5
		echo "That directory already exists." | pv -qL 21
		sleep .5
		echo "Please slect a different name." | pv -qL 21
		sleep .5
		read REPLY
		sleep .5
			if 
				[ -d "/run/media/$USER/$REPLY" ]
			then
				echo "That directory already exists." | pv -qL 21
				echo ""
				sleep 1
				echo "Please check names inside of /run/media/$USER and try again." | pv -qL 21
				sleep .5
				echo "Terminating tool." | pv -qL 21
				sleep 2
			else
				echo "Calling on 'mkdir' command." | pv -qL 21
				sleep .5
				sudo mkdir -v /run/media/$USER/$REPLY | pv -qL 21
				echo "All done!" | pv -qL 21
				sleep 1
				echo "Terminating tool." | pv -qL 21
				sleep 2
			fi
	else
		echo "Calling on 'mkdir' command." | pv -qL 21
		sleep .5
		sudo mkdir -v /run/media/$USER/$REPLY | pv -qL 21
		echo "All done!" | pv -qL 21
		sleep 1
		echo "Terminating tool." | pv -qL 21
		sleep 2
	fi
echo ""
